language: node_js
sudo: false
node_js:
  - 9
install:
  - yarn
script:
  - yarn tslint
  - yarn build
  - yarn test
cache: yarn
before_deploy:
  - openssl aes-256-cbc -K $encrypted_30952aa550a8_key -iv $encrypted_30952aa550a8_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
addons:
  ssh_known_hosts:
    - buttplug.world
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --rsync-path=”mkdir -p /home/buttplugworld/beta.buttplug.world/syncydink && rsync” --delete-after index.html dist buttplugworld@buttplug.world:/home/buttplugworld/beta.buttplug.world/syncydink
  on:
    branch: master
